sources:
  - name: MyOpenapiApi
    handler:
      openapi:
        source: ./cogniteV789.json
        baseUrl: https://{context.headers['x-cognite-cluster']}.cognitedata.com
        operationHeaders:
          Authorization: Bearer {context.headers['x-cognite-token']}
