sources:
  - name: MyOpenapiApi
    handler:
      openapi:
        source: ./cogniteV789.json
        baseUrl: "https://api.cognitedata.com"
        operationHeaders:
          Authorization: Bearer {context.headers['x-cognite-token']}